version: '3'

services:
  phpmyadmin:
    image: phpmyadmin
    container_name: keycloak_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - VIRTUAL_HOST=phpmyadmin.localhost
    depends_on:
      - db
    networks:
      - proxy-tier

  keycloak:
    volumes:
      - ./extensions/dpv-theme/src/main/resources/theme/dpv-theme:/opt/keycloak/themes/dpv-theme-dev
      - ./extensions/dpv-tool-theme/src/main/resources/theme/dpv-tool-theme:/opt/keycloak/themes/dpv-tool-theme-dev
    environment:
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"