version: '3'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - VIRTUAL_HOST=phpmyadmin.localhost
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - proxy-tier

  keycloak:
    volumes:
      - ./extensions/dpv-theme/src/main/resources/theme/dpv-theme:/opt/jboss/keycloak/themes/dpv-theme-dev
    environment:
      KEYCLOAK_WELCOME_THEME: "dpv-theme-dev"